name: PowerShell Script Analysis

on:
  push:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Install-Module PSScriptAnalyzer

    
      - name: Get environment variables
        shell: pwsh
        run: |
          gci env:
          write-output "$GITHUB_CONTEXT"

      - name: List directory contents
        shell: pwsh
        run: |
          gci | Select FullName

      - name: Run Script Analyzer
        shell: pwsh
        run: |
          $script = Join-Path $env:RUNNER_WORKSPACE ".github/workflows/script_analysis.ps1"
          $analysisResult = pwsh -ExecutionPolicy Bypass -File $script

          # Generate warnings for annotations
          $warnings = ""
          foreach ($violation in $analysisResult.Diagnostics) {
            if ($violation.Severity -ge "Warning") {
              $warnings += "- $($violation.File) ($($violation.Rule.Name)): $($violation.Message)"
            }
          }

          # Upload report as artifact
          $reportPath = Join-Path $env:RUNNER_WORKSPACE "script_analysis_report.txt"
          $analysisResult | ConvertTo-Json | Out-File $reportPath -Force
          # Upload-Artifact -Path $reportPath -Name script_analysis_report.txt

          # Annotate commit with warnings (optional severity filter)
          if ($warnings) {
            Write-Host "::warning:: Please review script quality issues:"
            Write-Host $warnings
            echo $warnings >> "${GITHUB_EVENT_PATH}/${env:RUNNER_OS}"
          }
      
      - name: Upload Script Analysis Report
        uses: actions/upload-artifact@v3
        with:
          name: script_analysis_report.txt
          path: "${env:RUNNER_WORKSPACE}/script_analysis_report.txt"