name: PowerShell Script Analysis

on:
  push:
  pull_request:

jobs:
  analyze:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install PSScriptAnalyzer
        shell: pwsh
        run: |
          Set-PSRepository PSGallery -InstallationPolicy Trusted
          Install-Module PSScriptAnalyzer

      - name: Analyze PowerShell Files and Modules
        shell: pwsh
        run: |
          ./script.ps1

      - name: Annotate Commit (Optional)
        shell: pwsh
        run: |
          $warnings = $analysisResults | Where-Object { $_.Diagnostics.Count -gt 0 } | Select-Object File, Rule, Message, Severity | Format-List
          if ($warnings) {
            Write-Host "::warning:: Please review script quality issues:"
            Write-Host $warnings
            echo $warnings >> "${GITHUB_EVENT_PATH}/${env:RUNNER_OS}"
          }